[project]
name = "circuito-policial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luis_criollo_uees", email = "luisxavier_23@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flet>=1.0.0",
    "pydantic>=2.13.5",
]

[project.scripts]
circuito-policial = "circuito_policial:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
